### ISSUE TITLE
개발환경 셋팅

### ISSUE THREAD

**Issue by YangHeeDong** [YangHeeDong/TerraProject#1]
### 구현필요사항 
- SprinBoot, Gradle, JPA
- dev, proj, test DB 설정 application.yml
- swagger UI
- 로깅
- README.md

### ToDo
- [x] SpringBoot, Gradle, JPA 구축
- [x] 개발 환경 별 DB 세팅
- [x] sagger UI 설치
- [x] 로깅 구축
- [x] README 업데이트
