### ISSUE TITLE
controller 완성 및 통합 테스트

### ISSUE THREAD

**Issue by YangHeeDong** [YangHeeDong/TerraProject#5]
### 구현필요사항 
- 컨트롤러 완성
- 각 메서드 별 통합 테스트 코드
  - 성공
  - 실패1 : 파라미터가 잘못된 경우
  - 실패2 : 시작시간이 종료시간보다 늦는 경우
  - 실패3 : 데이터 제공 기간이 만료된 경우

### ToDo
- [x] 컨트롤러 완성
- [x] 각 메서드 별 통합 테스트 코드
  - [x] 성공
  - [x] 실패1 : 파라미터가 잘못된 경우
  - [x] 실패2 : 시작시간이 종료시간보다 늦는 경우
  - [x] 실패3 : 데이터 제공 기간이 만료된 경우
