### ISSUE TITLE
요청 데이터 검증 및 데이터 조회 기간

### ISSUE THREAD

**Issue by YangHeeDong** [YangHeeDong/TerraProject#6]
### 구현필요사항 
- 각 컨트롤러 메서드 마다 요청 데이터 검증
- 데이터 조회 기간 검증
  - 분 단위 API : 최근 1주 데이터 제공
  - 시 단위 API : 최근 3달 데이터 제공
  - 일 단위 API : 최근 1년 데이터 제공

### ToDo
- [x] 각 컨트롤러 메서드 마다 요청 데이터 검증
- [x] 데이터 조회 기간 검증
  - [x] 분 단위 API : 최근 1주 데이터 제공
  - [x] 시 단위 API : 최근 3달 데이터 제공
  - [x] 일 단위 API : 최근 1년 데이터 제공
